'use strict';
app.directive('audioUpload', ['record', function (record) {
    return {
        templateUrl: 'audioUpload.html',
        replace: true,
        scope: {},
        link: function (scope) {

            scope.audioOptions = [
                { value: 0, text: 'Generated by a machine' },
                { value: 1, text: 'Generated by you' },
                { value: 2, text: 'No audio' }
            ];

            scope.selectedAudioOption = scope.audioOptions[0].value;

            scope.startRecording = function () {
                scope.recording = true;
                scope.recordedAudio = null;
                record.record();
            };

            scope.stopRecording = function () {
                scope.recording = false;
                record.get().then(function (recordedAudio) {
                    scope.recordedAudio = recordedAudio;
                });
            };
        }
    };
}]);