'use strict';
app.directive('audioUpload', ['$q', '$timeout', 'http', 'record', function ($q, $timeout, http, record) {
    return {
        templateUrl: 'audioUpload.html',
        replace: true,
        scope: {
            media: '=ngModel',
            sourceText: '=',
            onSubmitRequest: '='
        },
        link: function (scope) {

            refreshToken();
            initializeDataModel();

            scope.audioOptions = [
                {value: 0, text: 'Generated by a machine'},
                {value: 1, text: 'Generated by you'},
                {value: 2, text: 'No audio'}
            ];

            scope.selectedAudioOption = scope.media.type || scope.audioOptions[0].value;

            scope.startRecording = function () {
                scope.recording = true;
                scope.recordedAudio = null;
                record.record();
            };

            scope.stopRecording = function () {
                scope.recording = false;
                scope.toBeUpdated = true;
                record.get().then(function (recordedAudio) {
                    setRecordedAudio(recordedAudio.base64);
                });
            };

            scope.onSubmitRequest = function () {
                var file = scope.recordedAudio && scope.recordedAudio.base64,
                    uploadUrl = '/rest/audio/' + (scope.media._id || ''),
                    deferred = $q.defer();
                if (!file && scope.selectedAudioOption === 0) {
                    //scope.reEvaluateExternalAudio().then(function () {
                        submit(uploadUrl, file).then(function () {
                            deferred.resolve();
                        });
                    //});
                } else {
                    submit(uploadUrl, file).then(function () {
                        deferred.resolve();
                    });
                }
                return deferred.promise;
            };

            scope.onSelectedAudioOptionChange = function (selectedOption) {
                scope.media.type = selectedOption;
                scope.toBeDeleted = (selectedOption !== 1);
                if(scope.selectedAudioOption === 0) {
                    generateAutomaticAudio();
                    scope.recordedAudio = null;
                }
            };

            scope.reEvaluateExternalAudio = function () {
                var deferred = $q.defer();
                if (scope.selectedAudioOption === 0) {
                    generateAutomaticAudio().then(function () {
                        deferred.resolve();
                    });
                } else {
                    deferred.resolve();
                }
                return deferred.promise;
            };

            function initializeDataModel() {
                if(!scope.media) {
                    scope.media = {};
                }
                if(!scope.recordedAudio) {
                    scope.recordedAudio = null;
                }
            }

            function getSubmitHeaders() {
                return {
                    transformRequest: angular.identity,
                    headers: {'Content-Type': undefined}
                };
            }

            function submit(uploadUrl, file) {
                var fileDescriptor = new FormData();
                fileDescriptor.append('file', file);
                var deferred = $q.defer();
                cUDSubit(uploadUrl, fileDescriptor).then(function (media) {
                    onSubmitSuccess(media, deferred);
                }).catch(function () {
                    onSubmitError(deferred);
                });
                return deferred.promise;
            }

            function cUDSubit(uploadUrl, fileDescriptor) {
                if (!scope.media._id && fileDescriptor && !scope.toBeDeleted) { //The media doesn't exist yet
                    return http.post(uploadUrl, fileDescriptor, getSubmitHeaders());
                } else if (scope.media._id) { //The media already exists
                    return cUDSubitExistingMedia(uploadUrl, fileDescriptor);
                } else { //Nothing has been actually changed
                    return $q.when([scope.media]);
                }
            }

            function cUDSubitExistingMedia(uploadUrl, fileDescriptor) {
                if (scope.toBeDeleted) { //The existing media has been marked to be removed
                    delete scope.media._id;
                    return http.delete(uploadUrl);
                } else if (scope.toBeUpdated) { //The existing media has been marked to be updated
                    return http.put(uploadUrl, fileDescriptor, getSubmitHeaders());
                } else { //Nothing has been actually changed
                    return $q.when([scope.media]);
                }
            }

            function onSubmitSuccess(media, deferred) {
                refreshToken();
                scope.media._id = (media && media[0]) ? media[0]._id : undefined;
                $timeout(function () { //TODO: issue #9
                    deferred.resolve(media);
                }, 1000);
            }

            function onSubmitError(deferred) {
                deferred.reject();
            }

            function refreshToken() {
                scope.refreshToken = Math.floor(Math.random() * 10000);
            }

            function generateAutomaticAudio() {
                var deferred = $q.defer();
                http.get('/rest/external-audio?q=' + scope.sourceText).then(function (response) {
                    setRecordedAudio(response.data);
                    $timeout(function () {
                        deferred.resolve();
                    }, 1500);
                });
                return deferred.promise;
            }

            function setRecordedAudio(base64Data) {
                if(!scope.recordedAudio) {
                    scope.recordedAudio = {};
                }
                scope.recordedAudio.base64 = base64Data;
            }
        }
    };
}]);